### PR TITLE
feature: choose wallet directory

### LINKED ISSUE #256: a setting to specify or display the location of the wallet file
suggested by chappjc

### PR DESCRIPTION
**Pull request by JoeGruffins**
Just a rough draft.

This should offer three choices to use for your wallet dir.
I haven't tested using a sdcard yet, I need to find mine first...

This method differs from other preferences as it just uses an alert dialogue.  Should I make custom views?  The button on the create or load wallet screen should be different.  Still thinking about how to display it.

Feedback plz! If it's awful, I'll rework everything.  No worries.

closes #256

### CODE REVIEW

**Comment by JoeGruffins** [comment]
Setup activity

Choose settings dots that open menu, only one item at the moment
Choose change wallet directories opens alert dialogue with types of dirs, 2 or three depending on SD card state
A change presents another alert dialogue asking for confirmation, shows the absolute path or hidden in the case of the default location 
Cancel returns to the choices alert dialogue and resets to current directory. Ok will change preferences and restart app

screenshot_20190122-071643

Preferences activity
Choose directory option with hidden or absolute path
Tapping brings up same alert dialogue as before

screenshot_20190122-072427

If SD card is removed but the user had chosen it as directory, we toast and default to the default, private dir

screenshot_20190122-072540

**Comment by raedah** [comment]
At first glance this feature looks overly complex for most users and I dont see a clear value that it delivers.

**Comment by JoeGruffins** [comment]
@raedah 
issue #256 
I believe I said this before but the default wallet location cannot be touched by the user. Showing it is pointless. To make it accessable it must be moved to a public location. I believe the terminology I used in the ui explains this.

also gives user choice of three wallets which should close #188 as well

The biggest plus I see is the ability to choose the sdcard as a storage space which is, I would think, a desirable feature as the chain grows.

**Comment by raedah** [comment]
Closing for now due to inactivity. Can resurrect as needed.

**Pull request closed without merging**
