### PR TITLE
Overview page shows new transaction immediately

### PR DESCRIPTION
**Pull request by C-ollins**
This fixes issue #65

### CODE REVIEW

**Comment by raedah** [comment]
Appears not fixed in latest build. Still is requiring drag down to refresh. Also, transaction details view does not update. Change the number of required confirms to 2 for it to say status confirmed. (currently seeing 1)

**Comment by raedah** [comment]
The only thing remaining is proper sorting of pending items.

**Comment by raedah** [comment]
https://testnet.dcrdata.org/tx/a5f7d197ab016b956a4436a1d4f745e61851f0c10c9f5654a0cdec7caaa8b1ad
I sent 2.1 DCR.  dcrandroid shows 2.0999999 DCR.

**Comment by C-ollins** [comment]
The bug will be fixed in my next PR

**Pull request merged**
